/* ==========================================================================
   Etherfall - Global Constants & Tunables
   Central place for magic numbers used across systems. Keeping them here
   makes balancing and future content iteration straightforward.
   ========================================================================== */

export const GAME = {
  WIDTH: 1280,
  HEIGHT: 720,
  BACKGROUND_COLOR: "#0b0d12",
};

export const WORLD = {
  // A large, bounded playfield that feels "infinite" during normal play.
  WIDTH: 4000,
  HEIGHT: 4000,
};

export const PLAYER = {
  SPEED: 200, // fallback if player.json is missing
  MAX_HP: 100,
  RADIUS: 16,
  // Texture frame layout generated by the TextureManager.
  FRAME_WIDTH: 48,
  FRAME_HEIGHT: 64,
};

export const ENEMY = {
  SPEED: 40, // fallback speed if an enemy def omits `speed`
  RADIUS: 14, // collision radius
  EXP_REWARD: 10, // fallback EXP reward
};

// Progression (EXP) curve tuning. See utils/leveling.js for the formula.
// Tuned in v0.0.5.1 to make early levels feel slower so the player is never
// an instant god-mode: L1->L2 : 130  L2->L3 : 200  L3->L4 : 270 ...
export const EXP = {
  BASE: 130,
  STEP: 70,
};

// Combat tuning (v0.0.3). Knockback is an impulse (px/s) reduced by an
// entity's knockbackResistance (0 = full push, 1 = immune).
export const COMBAT = {
  PLAYER_IFRAME_MS: 500, // invincibility after taking a hit
  KNOCKBACK_FORCE: 260, // impulse applied to the player on contact
  CONTACT_DAMAGE_FALLBACK: 5, // used if player.json omits contactDamage
};

// Player Dash (v0.1.0). A short, high-speed burst triggered by SPACE with a
// cooldown and temporary i-frames. The burst speed is ~3x the player's normal
// movement speed (PLAYER.SPEED = 200) over a short window so the distance feels
// impactful but controlled.
export const DASH = {
  COOLDOWN_MS: 1500, // time between dashes
  DURATION_MS: 160, // length of the burst
  SPEED: 640, // burst speed in px/s (~3.2x PLAYER.SPEED)
  IFRAME_MS: 220, // invulnerability window (covers the whole burst + buffer)
};

// Enemy spawning tuning (used by EnemyManager).
export const SPAWN = {
  MARGIN: 80, // px outside the camera view where enemies appear
  BASE_INTERVAL: 1500, // ms between spawns at level 1
  MIN_INTERVAL: 400, // ms difficulty floor
  INTERVAL_DECAY: 15, // ms shaved off the interval per player level
  MAX_ENEMIES: 60, // hard cap on simultaneously active enemies
};

export const CAMERA = {
  LERP: 0.12, // follow smoothing
  ZOOM: 1,
};

export const STORAGE_KEYS = {
  SAVE: "etherfall.save.v1",
};

export const SCENES = {
  BOOT: "BootScene",
  PRELOAD: "PreloadScene",
  MAIN_MENU: "MainMenuScene",
  GAME: "GameScene",
  PAUSE: "PauseScene",
  GAME_OVER: "GameOverScene",
  CODEX: "CodexScene",
};

export const TEXTURE_KEYS = {
  PLAYER: "player",
  ENEMY: "enemy",
  GRASS: "grass-tile",
  PROJECTILE: "projectile",
};

// Projectile pool cap (v0.0.4). Pooled to avoid per-frame allocation.
export const PROJECTILE_POOL = 200;
