/* ==========================================================================
   Etherfall - Global Constants & Tunables
   Central place for magic numbers used across systems. Keeping them here
   makes balancing and future content iteration straightforward.
   ========================================================================== */

export const GAME = {
  WIDTH: 1280,
  HEIGHT: 720,
  BACKGROUND_COLOR: "#0b0d12",
};

export const WORLD = {
  // A large, bounded playfield that feels "infinite" during normal play.
  WIDTH: 4000,
  HEIGHT: 4000,
};

export const PLAYER = {
  SPEED: 200, // fallback if player.json is missing
  MAX_HP: 100,
  RADIUS: 16,
  // Texture frame layout generated by the TextureManager.
  FRAME_WIDTH: 48,
  FRAME_HEIGHT: 64,
};

export const ENEMY = {
  SPEED: 40, // fallback speed if an enemy def omits `speed`
  RADIUS: 14, // collision radius
  EXP_REWARD: 10, // fallback EXP reward
};

// Progression (EXP) curve tuning. See utils/leveling.js for the formula.
// The curve reproduces the v0.0.2 spec example:
//   L1->L2 : 100   L2->L3 : 150   L3->L4 : 200  (cumulative: 0/100/250/450)
export const EXP = {
  BASE: 100,
  STEP: 50,
};

// Enemy spawning tuning (used by EnemyManager).
export const SPAWN = {
  MARGIN: 80, // px outside the camera view where enemies appear
  BASE_INTERVAL: 1500, // ms between spawns at level 1
  MIN_INTERVAL: 400, // ms difficulty floor
  INTERVAL_DECAY: 15, // ms shaved off the interval per player level
  MAX_ENEMIES: 60, // hard cap on simultaneously active enemies
};

export const CAMERA = {
  LERP: 0.12, // follow smoothing
  ZOOM: 1,
};

export const STORAGE_KEYS = {
  SAVE: "etherfall.save.v1",
};

export const SCENES = {
  BOOT: "BootScene",
  PRELOAD: "PreloadScene",
  MAIN_MENU: "MainMenuScene",
  GAME: "GameScene",
  PAUSE: "PauseScene",
  GAME_OVER: "GameOverScene",
};

export const TEXTURE_KEYS = {
  PLAYER: "player",
  ENEMY: "enemy",
  GRASS: "grass-tile",
};
