/* ==========================================================================
   Etherfall - Global Constants & Tunables
   Central place for magic numbers used across systems. Keeping them here
   makes balancing and future content iteration straightforward.
   ========================================================================== */

export const GAME = {
  WIDTH: 1280,
  HEIGHT: 720,
  BACKGROUND_COLOR: "#0b0d12",
};

export const WORLD = {
  // A large, bounded playfield that feels "infinite" during normal play.
  WIDTH: 4000,
  HEIGHT: 4000,
};

export const PLAYER = {
  SPEED: 240,
  MAX_HP: 100,
  RADIUS: 16,
  // Texture frame layout generated by the TextureManager.
  FRAME_WIDTH: 48,
  FRAME_HEIGHT: 64,
};

export const ENEMY = {
  SPEED: 90,
  RADIUS: 14,
  // Spawn just outside the camera viewport by this margin (px).
  SPAWN_MARGIN: 80,
  BASE_SPAWN_INTERVAL: 1500, // ms
  MIN_SPAWN_INTERVAL: 350, // ms (difficulty floor)
  SPAWN_INTERVAL_STEP: 25, // ms removed per level
};

export const CAMERA = {
  LERP: 0.12, // follow smoothing
  ZOOM: 1,
};

export const STORAGE_KEYS = {
  SAVE: "etherfall.save.v1",
};

export const SCENES = {
  BOOT: "BootScene",
  PRELOAD: "PreloadScene",
  MAIN_MENU: "MainMenuScene",
  GAME: "GameScene",
  PAUSE: "PauseScene",
  GAME_OVER: "GameOverScene",
};

export const TEXTURE_KEYS = {
  PLAYER: "player",
  ENEMY: "enemy",
  GRASS: "grass-tile",
};
